name: Deploy Cookbook to S3

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install mbbook cli
        run: cargo install mdbook

      - name: Build mdbook
        run: mdbook build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Delete current book in S3
        run: |
          sleep 5
          aws s3 rm s3://${{ secrets.AWS_S3_STORAGE }}/ --recursive

      - name: Deploy build to S3
        run: |
          sleep 10
          aws s3 cp ./book s3://${{ secrets.AWS_S3_STORAGE }}/ --recursive
